kind: pipeline
name: MKDocs Test

trigger:
  repo:
    - ronggur/tinkerbell-docs
  event:
    - push
    - pull-request

steps:
  - name: test
    image: python:3
    commands:
    - pip install -r requirements.txt
    - pytest

  - name: write-good
    image: node:current-alpine
    commands:
      - yarn global add write-good --silent
      - write-good README.md
    depends_on: [clone]

  - name: markdownlint
    image: node:current-alpine
    commands:
      - yarn global add markdownlint-cli --silent
      - markdownlint README.md
    depends_on: [clone]

  - name: yamllint
    image: python:alpine
    commands:
      - pip3 install --quiet yamllint
      - yamllint  --config-file .yamllint.config --strict .*.yml
    depends_on: [clone]
