kind: pipeline
name: MKDocs Test

trigger:
  repo:
    - ronggur/tinkerbell-docs
  event:
    - push
    - pull-request

steps:
  - name: test
    image: python:3
    commands:
    - pip install mkdocs -r requirements.txt
    - pip install mkdocs-material
    - mkdocs build
